disabled_rules:
  - trailing_newline
  - unused_optional_binding
  - trailing_whitespace
  - closure_parameter_position

excluded:
  - Pods

function_parameter_count:
  - 10 #warning
  - 15 #error

identifier_name:
  min_length: 2
