identifier_name:
  min_length: 1

type_body_length:
  - 300 # warning
  - 400 # error

line_length:
  - 150
  - 200

disabled_rules:
 - force_try
 - function_body_length
 - type_body_length
 - file_length