type_body_length:
  - 300 # warning
  - 400 # error

line_length:
  - 150
  - 200

function_parameter_count:
  - 11
  - 15

disabled_rules:
 - force_try
 - function_body_length
 - type_body_length
 - file_length
 - trailing_whitespace
 - force_cast
 - closure_parameter_position
 - identifier_name
 - colon