identifier_name:
  min_length: 2

type_body_length:
  - 200 # warning
  - 300 # error

line_length:
  - 150
  - 200

function_parameter_count:
  - 11
  - 15

nesting_rule:
  - 2
  - null
  - 5
  - null

disabled_rules:
 - force_try
 - trailing_whitespace
 - closure_parameter_position